### ISSUE TITLE
Upgrade to sbt 1.0.0

### ISSUE THREAD

**Issue by jedesah** [slamdata/sbt-slamdata#30]
sbt 1.0.0 was released today. We should upgrade as soon as possible to get the potential incremental compiler improvements in Zinc

**Comment by drostron** [comment]
Once wartremover/wartremover#393 lands we should be ready to cross-publish for sbt 0.13.16 and 1.0.0.

https://github.com/slamdata/sbt-slamdata/compare/master...drostron:cross-build-sbt-1.0.0
